<?php

/**
 * Note to module developers:
 *  Keeping a module specific language file like this
 *  in this external folder is not a good practise for
 *  portability - I do not advice you to do this for
 *  your own modules since they are non-default.
 *  Instead, simply put your language files in
 *  application/modules/yourModule/language/
 *  You do not need to change any code, the system
 *  will automatically look in that folder too.
 */

// UCP
$lang['user_panel'] = "用户控制面板";
$lang['account_overview'] = "账户信息";
$lang['account_characters'] = "帐户角色";

$lang['nickname'] = "昵称";
$lang['change_nickname'] = "更改名称";

$lang['location'] = "位置";
$lang['change_location'] = "更改位置";

$lang['email'] = "邮箱";
$lang['change_email'] = "更改邮箱";

$lang['password'] = "密码";
$lang['change_password'] = "更改密码";

$lang['account_rank'] = "帐户等级";
$lang['voting_points'] = "投票点";
$lang['donation_points'] = "捐赠点";
$lang['account_status'] = "帐户状态";
$lang['member_since'] = "加入会员";
$lang['data_tip_vote'] = "通过为服务器投票获得投票积分";
$lang['data_tip_donate'] = "通过向服务器捐款获得捐赠积分";

$lang['edit'] = "编辑";

// Avatar
$lang['change_avatar'] = "更改头像";
$lang['avatar_invalid'] = "所选的头像无效";
$lang['avatar_invalid_rank'] = "所选化身需要更高的用户等级";

// Settings
$lang['settings'] = "账户设置";

$lang['old_password'] = "旧密码";
$lang['new_password'] = "新密码";
$lang['new_password_confirm'] = "确认密码";
$lang['new_password_submit'] = "更改密码";

$lang['nickname_error'] = "Nickname must be between 4 and 14 characters long and may only contain letters and numbers";
$lang['location_error'] = "Location may only be up to 32 characters long and may only contain letters";
$lang['pw_doesnt_match'] = "Passwords doesn't match!";
$lang['changes_saved'] = "Changes have been saved!";
$lang['invalid_pw'] = "Incorrect password!";
$lang['nickname_taken'] = "Nickname is already taken";
$lang['invalid_language'] = "Invalid language";

$lang['change_information'] = "更改资料";

// Security
$lang['account_security'] = "帐户安全";
$lang['save_changes'] = "保存更改";
$lang['two_factor'] = "TWO FACTOR AUTHENTICATION";
$lang['two_factor_description'] = "Two-factor authentication helps protect your account from unauthorized access by adding an additional layer of security.";
$lang['two_factor_help'] = "Download Google Authenticator app from Google Play or App Store. Launch the app and use your phone camera to scan the barcode below. Enter the 6 digit verification code generated by the Authenticator app.";
$lang['qr_code'] = "Qr code";
$lang['qr_code_help_1'] = "Unable to scan the Qrcode? You can also enter";
$lang['qr_code_help_2'] = "key manually.";
$lang['select_authentication'] = "Select authentication method";
$lang['disabled'] = "Disabled";
$lang['google_authenticator'] = "Google Authenticator";
$lang['six_digit_auth_code'] = "6 digit Authenticator code";
$lang['six_digit_not_empty'] = "6 digit Authenticator code cannot be empty";
$lang['six_digit_not_true'] = "Authenticator code is not true";
